# Copyright © 2017 Martin Ueding <dev@martin-ueding.de>
# Modified by Markus Werner <markus.werner@uni-bonn.de>
# Licensed under the MIT/Expat license.

language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - ./travis-ci.sh
dist: trusty
sudo: true
